png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datetime, global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(datetime, household$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime,household$Sub_metering_1,type="l", ylab="Energy sub metering", xlab="")
lines(datetime, household$Sub_metering_2, type="l", col="red")
lines(datetime, household$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(datetime, household$Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime")
dev.off()